version: "3.5"
services:
  postgres_tick3D:
    image: postgres:15
    container_name: postgres_tick3D
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db_tick3D:/var/lib/postgresql/data
    restart: always

  tick3D-be:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/ngyngcphu/tick3D-be:latest
    container_name: tick3D-be
    ports:
      - 8081:8080
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres_tick3D
    restart: always
  
volumes:
  postgres_db_tick3D:
