version: "3.5"
services:
  postgres_tick3d:
    image: postgres:15
    container_name: postgres_tick3d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_db_tick3d:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_db_tick3d:


